server:
  port: 9002

spring:
  datasource:
    username: root
    password: p@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect